name: crypto_bot
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  fluttertoast: ^8.1.3
  web_socket_channel: ^2.3.0
  intl: ^0.18.0
  infinite_scroll_pagination: ^3.2.0
  flutter_local_notifications: ^8.2.0
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

